language: julia
os:
  - linux
  - osx
  - windows
arch:
  - amd64
  - i686
  - arm64
  - arm32
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
  exclude:
    - os: osx
      arch: i686
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
    - os: windows
      arch: arm32
    - julia: nightly
      arch: arm64
    - os: windows
      arch: arm32
    - julia: nightly
      arch: arm32
notifications:
  email: false
after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
